# Profile information
name: Forde
title: Michael Forde's Blog
description: > # this means to ignore newlines until "baseurl:"
  This I my first blog, this will be more of a technical journal
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.forde.blog" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: michael.forde.3139
twitter: fordetek
github: fordetek
youtube: channel/UCwJPdoNsAk0EnaK4kejs1uA?view_as=subscriber

# Contact form
email: michael@fordetek.ie # change this manually in the contact.html located in _pages

# Comments
discus-identifier: blog-fordetek-ie

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
